apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chaitaleerahate/cloud-native-dotnet-app
    targetRevision: main
    path: cloudnative-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
